name: galaxeus
description: A library for interact with system galaxeus.
version: 0.0.5
homepage: https://github.com/azkadev/telegram_client/wiki
repository: https://github.com/azkadev/telegram_client/tree/main/dart/telegram_client
issue_tracker: https://github.com/azkadev/telegram_client/issues
publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: 
  # galaxeus_core_apis: ^0.0.5
  # galaxeus_lib: ^0.0.17
  galaxeus_core_apis:
    path: ../galaxeus_core_apis/
  galaxeus_lib:
    path: ../galaxeus_lib/